// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi_un41mHbnscbuS9DZIYzok5k-7gDbew',
    appId: '1:755285041313:web:d76b8bc3c69a2b5030d0e0',
    messagingSenderId: '755285041313',
    projectId: 'flappybird-c96c2',
    authDomain: 'flappybird-c96c2.firebaseapp.com',
    storageBucket: 'flappybird-c96c2.appspot.com',
    measurementId: 'G-NWEFTEZF14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIzgu5BQ3Ou_uoRopDu7dwrTZb-POhAug',
    appId: '1:755285041313:android:06db7bfc9d742fe930d0e0',
    messagingSenderId: '755285041313',
    projectId: 'flappybird-c96c2',
    storageBucket: 'flappybird-c96c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJmUI2ggo91PSCowngnd_lSyLyU6kS2_Y',
    appId: '1:755285041313:ios:e3a56d834c480e6c30d0e0',
    messagingSenderId: '755285041313',
    projectId: 'flappybird-c96c2',
    storageBucket: 'flappybird-c96c2.appspot.com',
    iosClientId: '755285041313-tm32vphasid33j92a415jg41imcsmrhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJmUI2ggo91PSCowngnd_lSyLyU6kS2_Y',
    appId: '1:755285041313:ios:e3a56d834c480e6c30d0e0',
    messagingSenderId: '755285041313',
    projectId: 'flappybird-c96c2',
    storageBucket: 'flappybird-c96c2.appspot.com',
    iosClientId: '755285041313-tm32vphasid33j92a415jg41imcsmrhj.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
